---
# tasks file for ansible-kibana
- name: Set facts
  ansible.builtin.include_tasks: set_facts.yml

- name: Debian specific tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: RHEL specific tasks
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Configure Kibana
  ansible.builtin.include_tasks: config.yml
  when: kibana['config']|bool

- name: Manage Kibana plugins
  ansible.builtin.include_tasks: plugins.yml

- name: Manage Kibana service
  ansible.builtin.include_tasks: service.yml
